### ISSUE TITLE
Composite keys

### ISSUE THREAD

**Issue by cemo** [jparams/data-store#18]
I think it would be cool to have a composite key support as well. 

Something like: 

```
Index<Person> index = store.index(IndexDefinition.withCompositeKeyMapping("MyNewName").with(Person::getFirstName).and(Person::getLastName));

store.getFirst(Query.where("MyNewName", "cemo", "koc"));

```

I am typing on phone please forgive my typos. :)

**Comment by jparams** [comment]
This is entirely possible by leveraging tuples or custom classes, as long as the hash code and equals are correctly implemented.

For example:
Index<Person> index = store.index("fullName", IndexDefinition.withKeyMapping(person -> new FullName(person.getFirstName(), person.getLastName()));

store.getFirst(Query.where("fullName", new FullName("cemo", "koc")));

**Comment by jparams** [comment]
Please re-open if solution does not seem reasonable
